### ISSUE TITLE
Meetup 1

### ISSUE THREAD

**Issue by mpsnp** [lamp-ios/meetup#2]
## Задачи

- [x] Сделать русский вариант readme
- [x] Описать требования к докладам
- [x] Собрать заявки на доклады
- [x] Сформировать программу митапа
- [x] Найти и забронировать место проведения
- [x] Создать страницу митапа (можно хостить на GitHub pages и использовать какой нибудь генератор статических сайтов типа как для бложиков)
- [x] Создать форму регистрации на TimePad
- [x] Анонсировать митап в Краснодарских IT сообществах

## Программа
1. #7 Поговорим о координаторах @vladislav-m
2. #5 Продвинутое использование Push-уведомлений. Часть 1 @AlexShik
3. #8 Однонаправленные архитектуры в iOS @mpsnp

**Comment by 0xtmphey** [comment]
Думаю ещё нужно решить о формате митапа и его длительности. От этого будет зависеть кол-во докладов)

**Comment by mpsnp** [comment]
Уже это обсуждали, пришли примерно к следующему:
- 2-4 доклада по 10-20 мин (минимум воды, максимум пользы), могут быть качественными вбросами.
- после каждого доклада 20-40 мин вопросов/обсуждений (нужно придумать как больше вовлекать народ)
- в процессе могут появиться хорошие вопросы. Если они обширные, то это отличная тема для докладов на следующем митапе, если нет и остается время, можно отложить так сказать до конца митапа и обсудить за круглым столом.
- после официальной части — afterparty, где продолжается нетворкинг.

**Comment by mpsnp** [comment]
@AlexShik @vladislav-m гляньте, устраивает очередность?

**Comment by vladislav-m** [comment]
мне норм

**Comment by vladislav-m** [comment]
Залил в репу презентацию от доклада https://github.com/lamp-ios/meetup/blob/master/%D0%9A%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D1%8B.pdf
Как думаете, куда их лучше складывать? Наверное под отдельный митап завести отдельные папочки и туда лить все доклады?

**Comment by mpsnp** [comment]
Да, я организую, и опишу формат, и процесс заливки и закрытия соответствующих issue.
