### ISSUE TITLE
Поговорим о координаторах

### ISSUE THREAD

**Issue by vladislav-m** [lamp-ios/meetup#7]
- базовые принципы построения проекта с координаторами
- плюсы и минусы
- опыт использования в продакшне

[презентация](https://github.com/lamp-ios/meetup/blob/master/%D0%9A%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D1%8B.pdf)

**Comment by mpsnp** [comment]
Будет код?) Я прям очень хочу послушать и посмотреть, потому что возможно я их просто не так готовил всю жизнь 😄

**Comment by vladislav-m** [comment]
Могу запилить и примеры кода. У меня даж есть полноценный экзампл проект годичной давности на MVVM+C
